### ISSUE TITLE
Set up Kanbad board

### ISSUE THREAD

**Issue by AbdollahRaafat** [AngomRanjan/recipe-app#12]
Hi, CR

I and @AngomRanjan are two group members.

We have made this [Kanban](https://github.com/AngomRanjan/recipe-app/projects/1)  to our rails group project.

please leave us some review about the board.

**Comment by descholar-ceo** [comment]
> Hi, CR
> 
> I and @AngomRanjan are two group members.
> 
> We have made this [Kanban](https://github.com/AngomRanjan/recipe-app/projects/1) to our rails group project.
> 
> please leave us some review about the board.

Hi @AbdollahRaafat && @AngomRanjan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] The kanban board is covering all tasks
- [ ] The project's cards are shared equitably

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
